import { Injectable } from '@angular/core';
import { Todo } from './todo';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  baseUrl = 'https://crudcrud.com/api/9f0bf62874984b0993a7dc49a8ca579f'; // berbeda untuk setiap mahasiswa

  constructor(private http: HttpClient) {}

  getTodo() {
    return this.http.get(`${this.baseUrl}/todo`);
  }

  getIdTodo(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/todo/${id}`);
  }

  postTodo(todos: Todo) {
    delete todos._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/todo`, todos);
  }

  updateTodo(todos: Todo) {
    const id = todos._id; // we copy the original id
    delete todos._id; // we delete the original id so the server doesn't reply with error message
    return this.http.put(`${this.baseUrl}/todo/${id}`, todos);
  }

  deleteTodo(todos: Todo) {
    const id = todos._id; // we copy the original id
    return this.http.delete(`${this.baseUrl}/todo/${id}`);
  }
}
